### ISSUE TITLE
Video progress slider time issue

### ISSUE THREAD

**Issue by samhogan** [P0werC0rd0fJustice/TheMildOnes-MediaPlayer#21]
For videos under 1:40, the progress slider stops before the end when the video finishes. If the video is longer, the slider reaches the end before the video is finished

**Comment by tbreetz** [comment]
Proposed solution: Only allow videos that are exactly 1:40 in length.

**Comment by tbreetz** [comment]
Fixed in [commit 532165](https://github.com/P0werC0rd0fJustice/TheMildOnes-MediaPlayer/commit/53216583983d5a303c864a7ef40a4486b74f519e)
